name: Sarif complete workflow
on:
  push:
    branches:
      - main
jobs:
  docker:
    permissions: write-all
    runs-on: self-hosted
    steps:
      # - name: Set up Docker1
      #   uses: crazy-max/ghaction-setup-docker@v3
      #   with:
      #     daemon-config: |
      #       {
      #         "debug": true,
      #         "experimental": true,
      #         "features": {
      #           "containerd-snapshotter": true
      #         }
      #       }
      # - name: Generate Dockerfile
      #   run: |
      #     echo -e "FROM alpine\nCMD ["echo", "Hello StackOverflow!"]" > Dockerfile
      #     ls
      #     pwd
      # - name: Download Qscanner
      #   run: |
      #     QSCANNER_URL=$(curl $proxy -s https://www.qualys.com/downloads/qscanner/ | grep -ai "gen_cask_artifacts" | sed 's/^.*https/https/' | sed 's/".*//')
      #     wget https://www.qualys.com/qscanner/download/v4.2.0/download_qscanner.sh
      #     ls -ltr
      #     pwd
      #     sudo bash $(pwd)/download_qscanner.sh
      # - name: Docker version
      #   run: docker info
      - name: Docker image pull
        run: sudo docker pull bkimminich/juice-shop:latest
      # - name: Docker qscanner image pull
      #   run: sudo docker pull art-hq.intranet.qualys.com:5001/qualys/internal/qscanner:4.3.0-12-dev-linux-amd64-1728887376
      # - name: Build Docker image
      #   run: |
      #     docker buildx create --use
      #     docker buildx inspect
      #     docker buildx build --file /home/runner/work/sarif/sarif/Dockerfile --platform linux/amd64,linux/arm64 -t crmtestimage:multiid --load .
      - name: List docker images
        run: sudo docker images
      - name: docker inspect
        run: |
         image_sha=$(sudo docker inspect -f '{{.Id}}' bkimminich/juice-shop:latest)
         echo "Image SHA: $image_sha"
         sudo docker history $image_sha
      # - name: save multi-arch image
      #   run: |
      #     image_sha=$(docker inspect -f '{{.Id}}' crmtestimage:multiid)
      #     echo "Image ID: $image_sha"
      #     docker save -o multiarchtest.tar $image_sha
      #     ls
      - name: Qscanner token
        run: |
         export QUALYS_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdWF5czlyczEwIiwiaXNzIjoicWFzIiwicG9ydGFsVXNlcklkIjo0OTA0ODczLCJzZWNyZXRJZCI6IjZkMjA1YjdjLWM3YmQtNDFjOC05MjZkLTVhNDgzZTE1ZmJmMCIsInF3ZWJVc2VySWQiOjE1NjIxODQsImF1ZCI6InFhcyIsImN1c3RvbWVySWQiOjEyNjYyMSwidXNlclV1aWQiOiI2ZGY1MmQwZi01NTFiLTQ1NTYtODFmMS00ZWRjNzQzMGNhYTAiLCJzdWJzY3JpcHRpb25VdWlkIjoiZWM2NGQ1ODktZjMyOS1kY2VjLTgyYTctODA0NTE1Yjg5MjA0IiwiZXhwIjoxNzgyMzY3NTM1LCJzdWJzY3JpcHRpb25JZCI6NDEsInRva2VuVHlwZSI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTc1MDgzMTUzNSwianRpIjoiMzY0YzY3MzItZWNmNy00NzdkLWJlMTctYTYyZGQwNjI1YjI4In0.KBHemQKJs5-K2Nc5VgEGfzSQo09jPsoHiRZF-nnaNR5blcBdldny76L4H6v8LeNBrurx1PwJnqU3sNRG1TCrcA
      - name: Image scan through Qscanner
        continue-on-error: true
        run: |
         image_sha=$(sudo docker inspect -f '{{.Id}}' bkimminich/juice-shop:latest)
         # sockpath=$(sudo docker info -f '{{.DockerRootDir}}')
         # sockpath=$(echo $sockpath | awk -v srch="data" -v repl="docker.sock" '{ sub(srch,repl,$0); print $0 }')
         # echo $sockpath
         echo "sudo /home/ubuntu/Qscanner-4.3/qscanner image $image_sha  --pod CA1 --access-token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdWF5czlyczEwIiwiaXNzIjoicWFzIiwicG9ydGFsVXNlcklkIjo0OTA0ODczLCJzZWNyZXRJZCI6IjZkMjA1YjdjLWM3YmQtNDFjOC05MjZkLTVhNDgzZTE1ZmJmMCIsInF3ZWJVc2VySWQiOjE1NjIxODQsImF1ZCI6InFhcyIsImN1c3RvbWVySWQiOjEyNjYyMSwidXNlclV1aWQiOiI2ZGY1MmQwZi01NTFiLTQ1NTYtODFmMS00ZWRjNzQzMGNhYTAiLCJzdWJzY3JpcHRpb25VdWlkIjoiZWM2NGQ1ODktZjMyOS1kY2VjLTgyYTctODA0NTE1Yjg5MjA0IiwiZXhwIjoxNzgyMzY3NTM1LCJzdWJzY3JpcHRpb25JZCI6NDEsInRva2VuVHlwZSI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTc1MDgzMTUzNSwianRpIjoiMzY0YzY3MzItZWNmNy00NzdkLWJlMTctYTYyZGQwNjI1YjI4In0.KBHemQKJs5-K2Nc5VgEGfzSQo09jPsoHiRZF-nnaNR5blcBdldny76L4H6v8LeNBrurx1PwJnqU3sNRG1TCrcA"
         sudo env DISABLE_SBOM_UPLOAD=yes env SHOW_RESPONSE_BODY_IN_BACKEND_ERROR=yes /home/ubuntu/Qscanner-4.3/qscanner image $image_sha  --pod CA1 --access-token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdWF5czlyczEwIiwiaXNzIjoicWFzIiwicG9ydGFsVXNlcklkIjo0OTA0ODczLCJzZWNyZXRJZCI6IjZkMjA1YjdjLWM3YmQtNDFjOC05MjZkLTVhNDgzZTE1ZmJmMCIsInF3ZWJVc2VySWQiOjE1NjIxODQsImF1ZCI6InFhcyIsImN1c3RvbWVySWQiOjEyNjYyMSwidXNlclV1aWQiOiI2ZGY1MmQwZi01NTFiLTQ1NTYtODFmMS00ZWRjNzQzMGNhYTAiLCJzdWJzY3JpcHRpb25VdWlkIjoiZWM2NGQ1ODktZjMyOS1kY2VjLTgyYTctODA0NTE1Yjg5MjA0IiwiZXhwIjoxNzgyMzY3NTM1LCJzdWJzY3JpcHRpb25JZCI6NDEsInRva2VuVHlwZSI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTc1MDgzMTUzNSwianRpIjoiMzY0YzY3MzItZWNmNy00NzdkLWJlMTctYTYyZGQwNjI1YjI4In0.KBHemQKJs5-K2Nc5VgEGfzSQo09jPsoHiRZF-nnaNR5blcBdldny76L4H6v8LeNBrurx1PwJnqU3sNRG1TCrcA --cache none -l debug --report-format sarif -o /home/ubuntu/Qscanner-4.3/sarif-reports/evaluate-policy -m evaluate-policy --scan-timeout 30m --skip-verify-tls --scan-types pkg,secret
      - name: Checkout repository
        uses: actions/checkout@v4 
      - name: Scan images from list
        continue-on-error: true
        run: |
         export QUALYS_ACCESS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdWF5czlyczEwIiwiaXNzIjoicWFzIiwicG9ydGFsVXNlcklkIjo0OTA0ODczLCJzZWNyZXRJZCI6IjZkMjA1YjdjLWM3YmQtNDFjOC05MjZkLTVhNDgzZTE1ZmJmMCIsInF3ZWJVc2VySWQiOjE1NjIxODQsImF1ZCI6InFhcyIsImN1c3RvbWVySWQiOjEyNjYyMSwidXNlclV1aWQiOiI2ZGY1MmQwZi01NTFiLTQ1NTYtODFmMS00ZWRjNzQzMGNhYTAiLCJzdWJzY3JpcHRpb25VdWlkIjoiZWM2NGQ1ODktZjMyOS1kY2VjLTgyYTctODA0NTE1Yjg5MjA0IiwiZXhwIjoxNzgyMzY3NTM1LCJzdWJzY3JpcHRpb25JZCI6NDEsInRva2VuVHlwZSI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTc1MDgzMTUzNSwianRpIjoiMzY0YzY3MzItZWNmNy00NzdkLWJlMTctYTYyZGQwNjI1YjI4In0.KBHemQKJs5-K2Nc5VgEGfzSQo09jPsoHiRZF-nnaNR5blcBdldny76L4H6v8LeNBrurx1PwJnqU3sNRG1TCrcA
         IMAGE_LIST_FILE=images.txt  
         while IFS= read -r image; do
         echo "Pulling & scanning $image"
         sudo docker pull $image
         image_sha=$(sudo docker inspect -f '{{.Id}}' $image)
         safe_image_name=$(echo $image | sed 's/[/:]/_/g')
         sudo env DISABLE_SBOM_UPLOAD=yes \
         env SHOW_RESPONSE_BODY_IN_BACKEND_ERROR=yes \
         /home/ubuntu/Qscanner-4.3/qscanner image $image_sha \
         --pod CA1 \
         --access-token $QUALYS_ACCESS_TOKEN \
         --report-format sarif \
         -o /home/ubuntu/Qscanner-4.3/sarif-reports/$safe_image_name \
         --scan-timeout 30m \
         --skip-verify-tls \
         -l debug \
         --scan-types pkg,secret \
         -m evaluate-policy \
         --storage-driver docker-overlay2
         #echo "Scan for $image completed. Sleeping 10 seconds..."
         #sleep 10
         echo "Deleting scanned image: $image"
         sudo docker rmi $image || true
         done < "$IMAGE_LIST_FILE"
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: /home/ubuntu/Qscanner-4.3/sarif-reports/evaluate-policy/520e3f10057c57a8b3dc0651ab5e9f8601938fc07f7112e397b3b92f4904f2b1-Report.sarif.json
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: my-analysis-tool
